#!/bin/sh

set -e

if [ -z "${DART_APT_CACHE}" ] ; then
  MIR_PREFIX="http://"
else
  MIR_PREFIX="${DART_APT_CACHE}/"
fi

MIR_REP="${MIR_PREFIX}http.debian.net/debian/"
MIR_SEC="${MIR_PREFIX}security.debian.org/"
DISTRO="jessie"
DART_HOSTNAME=${DART_HOSTNAME:-"dart"}
DART_USERNAME=${DART_USERNAME:-"user"}

export http_proxy=${DART_APT_CACHE}

lb config noauto \
  -a amd64 \
  -b hdd \
  --mode debian \
  --bootloader syslinux \
  --debian-installer false \
  -d ${DISTRO} \
  --memtest none \
  --apt-http-proxy "${DART_APT_CACHE}" \
  --parent-mirror-bootstrap ${MIR_REP} \
  --parent-mirror-chroot-security ${MIR_SEC} \
  --parent-mirror-binary ${MIR_REP} \
  --parent-mirror-binary-security ${MIR_SEC} \
  --mirror-bootstrap ${MIR_REP} \
  --mirror-chroot-security ${MIR_SEC} \
  --mirror-binary ${MIR_REP} \
  --mirror-binary-security ${MIR_SEC} \
  --keyring-packages "debian-archive-keyring kali-archive-keyring" \
  --firmware-binary true \
  --firmware-chroot true \
  --source false \
  --apt-indices false \
  --cache-packages false \
  --archive-areas 'main contrib non-free' \
  --bootappend-live "boot=live components noeject quiet nopersistence console=tty0 console=ttyS0,115200n8 hostname=${DART_HOSTNAME} username=${DART_USERNAME}" \
  "${@}"

# Creates the necessary autologin configuration for systemd. I didn't make hooks
# because I don't know how to get the live username during the chroot stage.
AUTOLOGIN_TERMS="tty0 tty1 tty2 tty3 tty4 tty5 tty6 ttyS0"
echo -n "${AUTOLOGIN_TERMS}" | xargs -I _ -n 1 -d " " ./create_autologin_conf _ "${DART_USERNAME}"
