#!/bin/sh

set -e

if [ -z "${DART_APT_CACHE}" ] ; then
  MIR_PREFIX="http://${DART_APT_CACHE}/"
else
  MIR_PREFIX="http://"
fi

MIR_REP="${MIR_PREFIX}http.debian.net/debian/"
MIR_SEC="${MIR_PREFIX}security.debian.org/"
DISTRO="wheezy"
HOSTNAME=${DART_HOSTNAME:-"dart"}
USERNAME=${DART_USER:-"user"}

export http_proxy=${DART_APT_CACHE}

lb config noauto \
  -a amd64 \
  -b hdd \
  --mode debian \
  --bootloader syslinux \
  --debian-installer false \
  -d ${DISTRO} \
  --memtest none \
  --apt-http-proxy ${DART_APT_CACHE} \
  --parent-mirror-bootstrap ${MIR_REP} \
  --parent-mirror-chroot-security ${MIR_SEC} \
  --parent-mirror-binary ${MIR_REP} \
  --parent-mirror-binary-security ${MIR_SEC} \
  --mirror-bootstrap ${MIR_REP} \
  --mirror-chroot-security ${MIR_SEC} \
  --mirror-binary ${MIR_REP} \
  --mirror-binary-security ${MIR_SEC} \
  --keyring-packages "debian-archive-keyring kali-archive-keyring" \
  --firmware-binary true \
  --firmware-chroot true \
  --source false \
  --apt-indices false \
  --cache-packages false \
  --archive-areas 'main contrib non-free' \
  --bootappend-live "boot=live live-config username=${USER} sudo openssh-server noeject quiet persistent console=tty0 console=ttyS0,115200n8 hostname=${HOSTNAME}" \
  "${@}"

